global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics

  - job_name: "ml-engine"
    static_configs:
      - targets: ["ml-engine:8001"]
    metrics_path: /metrics
